# Generated by Django 4.2.6 on 2023-10-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0010_loantransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='reason',
        ),
    ]
