# Generated by Django 4.2.6 on 2023-10-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0011_remove_loanrequest_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='status_date',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='due_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=14, max_digits=5),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='next_due',
            field=models.DateField(null=True),
        ),
    ]
