# Generated by Django 4.2.6 on 2023-10-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0012_remove_loanrequest_status_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
