# Generated by Django 4.2.6 on 2023-10-13 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0014_loantransaction_loan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loantransaction',
            old_name='loan_id',
            new_name='loan',
        ),
    ]
