# Generated by Django 4.2.6 on 2023-10-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0015_rename_loan_id_loantransaction_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransaction',
            name='loan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
