# Generated by Django 4.2.6 on 2023-10-13 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0016_alter_loantransaction_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransaction',
            name='loan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_loan_id', to='loanApp.loanrequest'),
        ),
    ]
