# Generated by Django 4.2.6 on 2023-10-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0018_alter_loantransaction_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='paid_months',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
