# Generated by Django 4.2.6 on 2023-10-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0020_alter_loanrequest_interest_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerLoan',
        ),
    ]
