# Generated by Django 4.2.6 on 2023-10-13 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_auto_20210902_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersignup',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customersignup',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='customersignup',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customersignup',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customersignup',
            name='information',
        ),
        migrations.RemoveField(
            model_name='customersignup',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customersignup',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customersignup',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customersignup',
            name='aadhar_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersignup',
            name='annual_income',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersignup',
            name='credit_score',
            field=models.PositiveIntegerField(default=300, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(300)]),
        ),
    ]
