# Generated by Django 4.2.6 on 2023-10-13 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginApp', '0003_remove_customersignup_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='aadhar_id',
            field=models.PositiveIntegerField(default=121212121212),
        ),
        migrations.AlterField(
            model_name='customersignup',
            name='annual_income',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
