# Generated by Django 4.2.6 on 2023-10-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0004_alter_customersignup_aadhar_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='aadhar_id',
            field=models.PositiveIntegerField(default=121212121212),
        ),
    ]
