# Generated by Django 4.2.6 on 2023-10-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0005_alter_customersignup_aadhar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='aadhar_id',
            field=models.PositiveIntegerField(blank=True, default=121212121212),
        ),
        migrations.AlterField(
            model_name='customersignup',
            name='annual_income',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
