# Generated by Django 4.2.6 on 2023-10-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0007_alter_customersignup_aadhar_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersignup',
            name='aadhar_id',
        ),
    ]
