# Generated by Django 4.2.6 on 2023-10-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0008_remove_customersignup_aadhar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersignup',
            name='aadhar_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
