# Generated by Django 4.2.6 on 2023-10-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0009_customersignup_aadhar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='aadhar_id',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
