# Generated by Django 4.2.6 on 2023-10-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0010_alter_customersignup_aadhar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='aadhar_id',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
