# Generated by Django 4.2.6 on 2023-10-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0011_remove_transaction_user_transaction_aadhar_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='aadhar_id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
